.build_template: &build_definition
  stage: build
  script:
    - dch -v $(git describe |tr '-' '.')~$(lsb_release -cs) -b ""
    - dpkg-buildpackage
    - mkdir artifacts
    - mv -v ../grase-conf-apache2_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

.test_template: &test_definition
  stage: test
  variables:
    DEBIAN_FRONTEND: noninteractive
  script:
    - apt-get update && apt-get install -y --no-install-recommends gdebi curl
    - gdebi -n artifacts/*.deb
    - mkdir -p /usr/share/grase/symfony4/public/
    - echo '<?php phpinfo() ?>' > /usr/share/grase/symfony4/public/index.php
    - service apache2 restart
    - curl -sv --fail localhost/grase/ > /dev/null


jessie-all:
  <<: *build_definition
  image: grase/build-images:jessie

# trusty-all:
#   <<: *build_definition
#   image: grase/build-images:trusty
#
# xenial-all:
#   <<: *build_definition
#   image: grase/build-images:xenial

bionic-all:
  <<: *build_definition
  image: grase/build-images:bionic

# Test all the packages

test:jessie-all:
  <<: *test_definition
  image: debian:jessie
  dependencies:
    - jessie-all

# test:trusty-all:
#   <<: *test_definition
#   image: ubuntu:trusty
#   dependencies:
#     - trusty-all
#
# test:xenial-all:
#   <<: *test_definition
#   image: ubuntu:xenial
#   dependencies:
#     - xenial-all

test:bionic-all:
  <<: *test_definition
  image: ubuntu:bionic
  dependencies:
    - bionic-all
