jessie-all:
  stage: build
  image: grase/build-images:jessie
  script:
    - dch -v $(git describe |tr '-' '.')~$(lsb_release -cs) -b ""
    - dpkg-buildpackage
    - mkdir artifacts
    - mv -v ../grase-conf-apache2_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

trusty-all:
  stage: build
  image: grase/build-images:trusty
  script:
    - dch -v $(git describe |tr '-' '.')~$(lsb_release -cs) -b ""
    - dpkg-buildpackage
    - mkdir artifacts
    - mv -v ../grase-conf-apache2_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

xenial-all:
  stage: build
  image: grase/build-images:xenial
  script:
    - dch -v $(git describe |tr '-' '.')~$(lsb_release -cs) -b ""
    - dpkg-buildpackage
    - mkdir artifacts
    - mv -v ../grase-conf-apache2_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

test:jessie-all:
  stage: test
  image: debian:jessie
  script:
    - apt-get install -y gdebi
    - gdebi -n artifacts/*.deb
  dependencies:
    - jessie-all

test:trusty-all:
  stage: test
  image: ubuntu:trusty
  script:
    - apt-get install -y gdebi
    - gdebi -n artifacts/*.deb
  dependencies:
    - trusty-all

test:xenial-all:
  stage: test
  image: ubuntu:xenial
  script:
    - apt-get install -y gdebi
    - gdebi -n artifacts/*.deb
  dependencies:
    - xenial-all
