#!/bin/bash

set -e
#set -u

action="$1"

if [ "$action" != configure ]
  then
  exit 0
fi

#DEBHELPER#

a2enmod rewrite || true
a2enmod headers || true

if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
        . /usr/share/apache2/apache2-maintscript-helper
        apache2_invoke enconf grase-conf-apache2.conf
elif  dpkg-query -f '${Version}'  -W 'apache2.2-common' > /dev/null 2>&1 ; then
        # if the configuration uses <IfVersion> uncomment the next line
        # a2enmod -q version
        [ -d /etc/apache2/conf.d/ ] && [ ! -L /etc/apache2/conf.d/grase-conf-apache2.conf ] && ln -s ../conf-available/grase-conf-apache2.conf /etc/apache2/conf.d/grase-conf-apache2.conf
fi



if which invoke-rc.d >/dev/null 2>&1; then
       invoke-rc.d apache2 restart 3>&- || true
else
       /etc/init.d/apache2 restart 3>&- || true
fi

exit 0
